---
title: "Processing BHRC data (test)"
author: "Gabriele Jobim"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Settings

```{r}
# setwd("C:/Users/gabri/Documents/mheg_mfq_clinical")
#install.packages("ipw")
#install.packages("twang")
#install.packages("mice")
#install.packages("WeightIt")

# Loading packages
library(tidyverse)
library(ggplot2)
library(readxl)
library(dplyr)
library(knitr)
library(sjPlot)
library(table1)
library(ipw)
library(mice)
library(WeightIt)

# BHRC Dictionary
bhrc_dictionary <- read_excel("data/bhrc_dictionary.xlsx")

# Loading .Rds databases
test_database <- readRDS("data/test_BHRCS_Clinical_Scales_Project_all.Rds")
test_database_mfq <- readRDS("data/test_Loneliness_Depression_data.Rds")
```

## Replacing missing MFQ data

```{r}
## Selecting wave==1
test_database_wave1 <- test_database[test_database$wave == "1", ]

## Selecting wave==2
test_database_wave2 <- test_database[test_database$wave == "2", ]

## Selecting wave==3 (n=2511)
test_database <- test_database[test_database$wave == "3", ]

## Selecting MFQ data | NOT AVAILABLE 
head(
  select(test_database, p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13, p_mfqtot)
)

## Replacing missing MFQ data

# Selecting wave==3 (n=2511)
test_database_mfq <- test_database_mfq[test_database_mfq$wave == "3", ]
test_database_mfq <- test_database_mfq %>%
  select(ident, p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13)
 
test_database <- test_database %>%
  select(-p_mfq1, -p_mfq2, -p_mfq3, -p_mfq4, -p_mfq5, -p_mfq6, -p_mfq7, -p_mfq8, -p_mfq9, -p_mfq10, -p_mfq11, -p_mfq12, -p_mfq13, -p_mfqtot)

# Joining by ident
bhrc_database <- left_join(test_database, test_database_mfq, by="ident")

bhrc_database <- bhrc_database |> 
  mutate(across(p_mfq1:p_mfq13, as.numeric)) |> 
  rowwise() |> 
  mutate(p_mfqtot = sum(c(p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13)))

# SCARED, SDQ, CBCL are fine
```

## Baseline characteristics

```{r}
test_database_wave1 <- test_database_wave1 %>%
  select(subjectid:abepstrat)

test_database_wave1 <- test_database_wave1 %>%
  select(-Sampling_weight, -Age_group_3cat, -Age_group_adult, -Age_group_2cat, -School_repet:-School_susp, -work_bin, -NEET_15, -Educ_years, -IQ_resid:-BMI, -work, -Assistance_amount, -Assistance_cash_transfer, -reg39b, -Income_others, -Birth_preg_dur:-prematurity_levc)

test_database_wave1$Gender <- as_factor(test_database_wave1$Gender)
test_database_wave1$Selection <- as_factor(test_database_wave1$Selection)
test_database_wave1$Site <- as_factor(test_database_wave1$Site)
test_database_wave1$Child_race <- as_factor(test_database_wave1$Child_race)
test_database_wave1$Child_race_2cat <- as_factor(test_database_wave1$Child_race_2cat)
test_database_wave1$minstlevel_4cat <- as_factor(test_database_wave1$minstlevel_4cat)
test_database_wave1$SEG <- as_factor(test_database_wave1$SEG)
test_database_wave1$Studying <- as_factor(test_database_wave1$Studying)
test_database_wave1$Educ_level_current <- as_factor(test_database_wave1$Educ_level_current)
test_database_wave1$Educ_attainment <- as_factor(test_database_wave1$Educ_attainment)
test_database_wave1$NEET_all <- as_factor(test_database_wave1$NEET_all)
test_database_wave1$instlevel <- as_factor(test_database_wave1$instlevel)
test_database_wave1$minstlevel <- as_factor(test_database_wave1$minstlevel)
test_database_wave1$finstlevel <- as_factor(test_database_wave1$finstlevel)
test_database_wave1$moccupation <- as_factor(test_database_wave1$moccupation)
test_database_wave1$foccupation <- as_factor(test_database_wave1$foccupation)
test_database_wave1$Assistance_any <- as_factor(test_database_wave1$Assistance_any)
test_database_wave1$Assistance_type <- as_factor(test_database_wave1$Assistance_type)
test_database_wave1$Conviction <- as_factor(test_database_wave1$Conviction)
test_database_wave1$Maternal_DIAG_ANY <- as_factor(test_database_wave1$Maternal_DIAG_ANY)
test_database_wave1$abepstrat <- as_factor(test_database_wave1$abepstrat)
```

## Manipulating database

### Converting into factors

```{r}
# Converting into factors
colnames(bhrc_database)
bhrc_database$Gender <- as_factor(bhrc_database$Gender)
bhrc_database$Selection <- as_factor(bhrc_database$Selection)
bhrc_database$Site <- as_factor(bhrc_database$Site)
bhrc_database$Child_race <- as_factor(bhrc_database$Child_race)
bhrc_database$Child_race_2cat <- as_factor(bhrc_database$Child_race_2cat)

bhrc_database$Age_group_3cat <- as_factor(bhrc_database$Age_group_3cat)
bhrc_database$Age_group_adult <- as_factor(bhrc_database$Age_group_adult)
bhrc_database$Age_group_2cat <- as_factor(bhrc_database$Age_group_2cat)
bhrc_database$minstlevel_4cat <- as_factor(bhrc_database$minstlevel_4cat)
bhrc_database$SEG <- as_factor(bhrc_database$SEG)

bhrc_database$School_repet <- as_factor(bhrc_database$School_repet)
bhrc_database$School_exp <- as_factor(bhrc_database$School_exp)
bhrc_database$School_drop <- as_factor(bhrc_database$School_drop)
bhrc_database$School_evasion <- as_factor(bhrc_database$School_evasion)
bhrc_database$School_susp <- as_factor(bhrc_database$School_susp)
bhrc_database$Studying <- as_factor(bhrc_database$Studying)
bhrc_database$Educ_level_current <- as_factor(bhrc_database$Educ_level_current)
bhrc_database$Educ_attainment <- as_factor(bhrc_database$Educ_attainment)

bhrc_database$work_bin <- as_factor(bhrc_database$work_bin)
bhrc_database$NEET_all <- as_factor(bhrc_database$NEET_all)
bhrc_database$NEET_15 <- as_factor(bhrc_database$NEET_15)

bhrc_database$IQ_group <- as_factor(bhrc_database$IQ_group)
bhrc_database$BMI_cat <- as_factor(bhrc_database$BMI_cat)

bhrc_database$instlevel <- as_factor(bhrc_database$instlevel)
bhrc_database$minstlevel <- as_factor(bhrc_database$minstlevel)
bhrc_database$finstlevel <- as_factor(bhrc_database$finstlevel)
bhrc_database$work <- as_factor(bhrc_database$work)
bhrc_database$moccupation <- as_factor(bhrc_database$moccupation)
bhrc_database$foccupation <- as_factor(bhrc_database$foccupation)

bhrc_database$Assistance_any <- as_factor(bhrc_database$Assistance_any)
bhrc_database$Assistance_type <- as_factor(bhrc_database$Assistance_type)
bhrc_database$Assistance_cash_transfer <- as_factor(bhrc_database$Assistance_cash_transfer)
bhrc_database$reg39b <- as_factor(bhrc_database$reg39b)

bhrc_database$Conviction <- as_factor(bhrc_database$Conviction)

bhrc_database$abepstrat <- as_factor(bhrc_database$abepstrat)

bhrc_database$med_lifetime <- as_factor(bhrc_database$med_lifetime)
bhrc_database$med_current <- as_factor(bhrc_database$med_current)
bhrc_database$Current_substance_use <- as_factor(bhrc_database$Current_substance_use)

bhrc_database$Service_Emergency_ever <- as_factor(bhrc_database$Service_Emergency_ever)
bhrc_database$Service_Psych_admission <- as_factor(bhrc_database$Service_Psych_admission)
bhrc_database$Service_Psych_admission_last_year <- as_factor(bhrc_database$Service_Psych_admission_last_year)

# Columns 129 to 136: WE1 até WE-Total
# Columns 141 to 151: DSH1 até DSH11

bhrc_database$Self_harm_any <- as_factor(bhrc_database$Self_harm_any)
bhrc_database$Self_harm_needed_care <- as_factor(bhrc_database$Self_harm_needed_care)
bhrc_database$Pregnant_ever <- as_factor(bhrc_database$Pregnant_ever)

bhrc_database$DIAG_ANY <- as_factor(bhrc_database$DIAG_ANY)
bhrc_database$DIAG_SEP_ANX <- as_factor(bhrc_database$DIAG_SEP_ANX)
bhrc_database$DIAG_SPEC_PHOB <- as_factor(bhrc_database$DIAG_SPEC_PHOB)
bhrc_database$DIAG_SOC_PHOB <- as_factor(bhrc_database$DIAG_SOC_PHOB)
bhrc_database$DIAG_PANIC <- as_factor(bhrc_database$DIAG_PANIC)
bhrc_database$DIAG_AGORAPHOB <- as_factor(bhrc_database$DIAG_AGORAPHOB)
bhrc_database$DIAG_PTSD <- as_factor(bhrc_database$DIAG_PTSD)
bhrc_database$DIAG_OCD <- as_factor(bhrc_database$DIAG_OCD)
bhrc_database$DIAG_GEN_ANX <- as_factor(bhrc_database$DIAG_GEN_ANX)
bhrc_database$DIAG_Other_ANX <- as_factor(bhrc_database$DIAG_Other_ANX)
bhrc_database$DIAG_DMDD <- as_factor(bhrc_database$DIAG_DMDD)
bhrc_database$DIAG_INHAT <- as_factor(bhrc_database$DIAG_INHAT)
bhrc_database$DIAG_DEP <- as_factor(bhrc_database$DIAG_DEP)
bhrc_database$DIAG_MANIA <- as_factor(bhrc_database$DIAG_MANIA)
bhrc_database$DIAG_ADHD <- as_factor(bhrc_database$DIAG_ADHD)
bhrc_database$DIAG_CD <- as_factor(bhrc_database$DIAG_CD)
bhrc_database$DIAG_ODD <- as_factor(bhrc_database$DIAG_ODD)
bhrc_database$DIAG_EAT <- as_factor(bhrc_database$DIAG_EAT)
bhrc_database$DIAG_AUTISM <- as_factor(bhrc_database$DIAG_AUTISM)
bhrc_database$DIAG_TIC <- as_factor(bhrc_database$DIAG_TIC)
bhrc_database$DIAG_PSYCH <- as_factor(bhrc_database$DIAG_PSYCH)

# Columns 176:185 - Broad_... (already factors)

bhrc_database$dummy_DIAG_comorbid <- as_factor(bhrc_database$dummy_DIAG_comorbid)
bhrc_database$dummy_Broad_comorbid <- as_factor(bhrc_database$dummy_Broad_comorbid)

# Columns 190:195 - pSDQ (short version)
# Columns 202-207 - sSDQ (short version)
# Columns 208 to 340 - ABCL (already factors)
# Columns 341 to 461 - CBCL (already factors)

bhrc_database$Dead <- as_factor(bhrc_database$Dead)
bhrc_database$Death_cause <- as_factor(bhrc_database$Death_cause)
bhrc_database$Suicide_selfharm_current <- as_factor(bhrc_database$Suicide_selfharm_current)
bhrc_database$Suicide_selfharm_lifetime <- as_factor(bhrc_database$Suicide_selfharm_lifetime)
bhrc_database$Suicide_thought_current_parent_report <- as_factor(bhrc_database$Suicide_thought_current_parent_report)
bhrc_database$Suicide_talk_current_parent_report <- as_factor(bhrc_database$Suicide_talk_current_parent_report)
bhrc_database$Suicide_selfharm_current_parent_report <- as_factor(bhrc_database$Suicide_selfharm_current_parent_report)
bhrc_database$Suicide_selfharm_lifetime_parent_report <- as_factor(bhrc_database$Suicide_selfharm_lifetime_parent_report)
bhrc_database$Suicide_thought_current_self_report <- as_factor(bhrc_database$Suicide_thought_current_self_report)
bhrc_database$Suicide_talk_current_self_report <- as_factor(bhrc_database$Suicide_talk_current_self_report)
bhrc_database$Suicide_selfharm_current_self_report <- as_factor(bhrc_database$Suicide_selfharm_current_self_report)
bhrc_database$Suicide_selfharm_lifetime_self_report <- as_factor(bhrc_database$Suicide_selfharm_lifetime_self_report)

# Columns 476:491 - CBCL scores and DAWBA/CBCL categories (already factors)
# Columns 492:495 - DAWBA/CBCL classifications (already factors)

bhrc_database$Suicide_severe_dsh_self <- as_factor(bhrc_database$Suicide_severe_dsh_self)
bhrc_database$Any_lifethreatening_outcome <- as_factor(bhrc_database$Any_lifethreatening_outcome)
bhrc_database$AUDIT_cat <- as_factor(bhrc_database$AUDIT_cat)
bhrc_database$Substance_lastyear <- as_factor(bhrc_database$Substance_lastyear)
bhrc_database$Any_poorLC_outcome <- as_factor(bhrc_database$Any_poorLC_outcome)
bhrc_database$Pregnant_adolesc <- as_factor(bhrc_database$Pregnant_adolesc)
bhrc_database$Substance_illegal_lastyear <- as_factor(bhrc_database$Substance_illegal_lastyear)

bhrc_database$WE_Total_bin_5 <- as_factor(bhrc_database$WE_Total_bin_5)
bhrc_database$WE_Total_bin_10 <- as_factor(bhrc_database$WE_Total_bin_10)
bhrc_database$pSDQ_Impact_bin_5 <- as_factor(bhrc_database$pSDQ_Impact_bin_5)
bhrc_database$pSDQ_Impact_bin_10 <- as_factor(bhrc_database$pSDQ_Impact_bin_10)

bhrc_database$Missing_LT <- as_factor(bhrc_database$Missing_LT)
bhrc_database$Missing_LC <- as_factor(bhrc_database$Missing_LC)

# p_mfqtot = sum later

# Columns 517-557 - SCARED items
# Columns 558-599 - Parent SDQ items 
# Columns 600-637 - Teacher SDQ items 
# Columns 638-677 - Self-report SDQ items 
# Columns 678-690 - MFQ items 
```

### Dropping columns

```{r}

# Dropping empty columns
bhrc_database <- bhrc_database %>%
    select(-Birth_weight, -ExecDisf_p10, -Income_others, -Birth_preg_dur, -gestagec, -birthweight, -Birth_premature, -Birth_delivery, -gsmoke_levc, -gdrink_levc, -breastf_levc, -prematurity_levc, -Maternal_DIAG_ANY, -tSDQ_Emo, -tSDQ_Con, -tSDQ_Hyp, -tSDQ_Peer, -tSDQ_Prosoc, -tSDQ_Impact, -Missing_w1, -Missing_w2, -tSDQ_1:-t1impact)

# Columns 68 to 125 - parent substance use 
bhrc_database <- bhrc_database %>%
    select(-p_alcohol_age:-p_amphet_year)

# Columns not being used
bhrc_database <- bhrc_database %>%
    select(-wm_fl, -ic_fl, -tp_fl, -ef_fl)

```

### Descriptive - diagnoses (wave2 and wave3)

```{r}
# Diagnostic - wave==2
test_database_wave2 <- test_database_wave2 %>%
  select(Gender, DIAG_ANY, DIAG_SEP_ANX, DIAG_SPEC_PHOB, DIAG_SOC_PHOB, DIAG_PANIC, DIAG_AGORAPHOB, DIAG_PTSD, DIAG_OCD, DIAG_GEN_ANX, DIAG_Other_ANX, DIAG_DMDD, DIAG_INHAT, DIAG_DEP, DIAG_MANIA, DIAG_ADHD, DIAG_CD, DIAG_ODD, DIAG_EAT, DIAG_AUTISM, DIAG_TIC, DIAG_PSYCH)

test_database_wave2 <- test_database_wave2 %>% drop_na()

#label(df$renda) <- "Renda mensal"
#label(df$estcivil) <- "Estado civil"

test_database_wave2$DIAG_ANY <- as_factor(test_database_wave2$DIAG_ANY)
test_database_wave2$DIAG_SEP_ANX <- factor(test_database_wave2$DIAG_SEP_ANX, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
# Substitua cada variável na lista pelo padrão fornecido

test_database_wave2$DIAG_SPEC_PHOB <- factor(test_database_wave2$DIAG_SPEC_PHOB, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave2$DIAG_SOC_PHOB <- factor(test_database_wave2$DIAG_SOC_PHOB, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave2$DIAG_PANIC <- factor(test_database_wave2$DIAG_PANIC, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave2$DIAG_AGORAPHOB <- factor(test_database_wave2$DIAG_AGORAPHOB, levels = c(0, 1),
                                              labels = c("No", "Yes"))

# Continue aplicando o padrão para cada variável...

test_database_wave2$DIAG_PTSD <- factor(test_database_wave2$DIAG_PTSD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave2$DIAG_OCD <- factor(test_database_wave2$DIAG_OCD, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave2$DIAG_GEN_ANX <- factor(test_database_wave2$DIAG_GEN_ANX, levels = c(0, 1),
                                           labels = c("No", "Yes"))

test_database_wave2$DIAG_Other_ANX <- factor(test_database_wave2$DIAG_Other_ANX, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave2$DIAG_DMDD <- factor(test_database_wave2$DIAG_DMDD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave2$DIAG_INHAT <- factor(test_database_wave2$DIAG_INHAT, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave2$DIAG_DEP <- factor(test_database_wave2$DIAG_DEP, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave2$DIAG_MANIA <- factor(test_database_wave2$DIAG_MANIA, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave2$DIAG_ADHD <- factor(test_database_wave2$DIAG_ADHD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave2$DIAG_CD <- factor(test_database_wave2$DIAG_CD, levels = c(0, 1),
                                       labels = c("No", "Yes"))

test_database_wave2$DIAG_ODD <- factor(test_database_wave2$DIAG_ODD, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave2$DIAG_EAT <- factor(test_database_wave2$DIAG_EAT, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave2$DIAG_AUTISM <- factor(test_database_wave2$DIAG_AUTISM, levels = c(0, 1),
                                           labels = c("No", "Yes"))

test_database_wave2$DIAG_TIC <- factor(test_database_wave2$DIAG_TIC, levels = c(0, 1),
                                       labels = c("No", "Yes"))

test_database_wave2$DIAG_PSYCH <- factor(test_database_wave2$DIAG_PSYCH, levels = c(0, 1),
                                         labels = c("No", "Yes"))

table1(~DIAG_ANY + DIAG_SEP_ANX + DIAG_SPEC_PHOB + DIAG_SOC_PHOB + DIAG_PANIC + DIAG_AGORAPHOB + DIAG_PTSD + DIAG_OCD + DIAG_GEN_ANX + DIAG_Other_ANX + DIAG_DMDD + DIAG_INHAT + DIAG_DEP + DIAG_MANIA + DIAG_ADHD + DIAG_CD + DIAG_ODD + DIAG_EAT + DIAG_AUTISM + DIAG_TIC +  DIAG_PSYCH | Gender, data = test_database_wave2)

# Diagnostic - wave==3
test_database_wave3 <- bhrc_database %>%
  select(Gender, DIAG_ANY, DIAG_SEP_ANX, DIAG_SPEC_PHOB, DIAG_SOC_PHOB, DIAG_PANIC, DIAG_AGORAPHOB, DIAG_PTSD, DIAG_OCD, DIAG_GEN_ANX, DIAG_Other_ANX, DIAG_DMDD, DIAG_INHAT, DIAG_DEP, DIAG_MANIA, DIAG_ADHD, DIAG_CD, DIAG_ODD, DIAG_EAT, DIAG_AUTISM, DIAG_TIC, DIAG_PSYCH)

test_database_wave3$DIAG_ANY <- as.factor(test_database_wave3$DIAG_ANY)
test_database_wave3$DIAG_SEP_ANX <- factor(test_database_wave3$DIAG_SEP_ANX, levels=c(0, 1),
         labels=c("No", "Yes"))

# Substitua cada variável na lista pelo padrão fornecido

test_database_wave3$DIAG_SPEC_PHOB <- factor(test_database_wave3$DIAG_SPEC_PHOB, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave3$DIAG_SOC_PHOB <- factor(test_database_wave3$DIAG_SOC_PHOB, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave3$DIAG_PANIC <- factor(test_database_wave3$DIAG_PANIC, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave3$DIAG_AGORAPHOB <- factor(test_database_wave3$DIAG_AGORAPHOB, levels = c(0, 1),
                                              labels = c("No", "Yes"))

# Continue aplicando o padrão para cada variável...

test_database_wave3$DIAG_PTSD <- factor(test_database_wave3$DIAG_PTSD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave3$DIAG_OCD <- factor(test_database_wave3$DIAG_OCD, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave3$DIAG_GEN_ANX <- factor(test_database_wave3$DIAG_GEN_ANX, levels = c(0, 1),
                                           labels = c("No", "Yes"))

test_database_wave3$DIAG_Other_ANX <- factor(test_database_wave3$DIAG_Other_ANX, levels = c(0, 1),
                                             labels = c("No", "Yes"))

test_database_wave3$DIAG_DMDD <- factor(test_database_wave3$DIAG_DMDD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave3$DIAG_INHAT <- factor(test_database_wave3$DIAG_INHAT, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave3$DIAG_DEP <- factor(test_database_wave3$DIAG_DEP, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave3$DIAG_MANIA <- factor(test_database_wave3$DIAG_MANIA, levels = c(0, 1),
                                          labels = c("No", "Yes"))

test_database_wave3$DIAG_ADHD <- factor(test_database_wave3$DIAG_ADHD, levels = c(0, 1),
                                         labels = c("No", "Yes"))

test_database_wave3$DIAG_CD <- factor(test_database_wave3$DIAG_CD, levels = c(0, 1),
                                       labels = c("No", "Yes"))

test_database_wave3$DIAG_ODD <- factor(test_database_wave3$DIAG_ODD, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave3$DIAG_EAT <- factor(test_database_wave3$DIAG_EAT, levels = c(0, 1),
                                        labels = c("No", "Yes"))

test_database_wave3$DIAG_AUTISM <- factor(test_database_wave3$DIAG_AUTISM, levels = c(0, 1),
                                           labels = c("No", "Yes"))

test_database_wave3$DIAG_TIC <- factor(test_database_wave3$DIAG_TIC, levels = c(0, 1),
                                       labels = c("No", "Yes"))

test_database_wave3$DIAG_PSYCH <- factor(test_database_wave3$DIAG_PSYCH, levels = c(0, 1),
                                         labels = c("No", "Yes"))


test_database_wave3 <- test_database_wave3 %>% drop_na()

table1(~DIAG_ANY + DIAG_SEP_ANX + DIAG_SPEC_PHOB + DIAG_SOC_PHOB + DIAG_PANIC + DIAG_AGORAPHOB + DIAG_PTSD + DIAG_OCD + DIAG_GEN_ANX + DIAG_Other_ANX + DIAG_DMDD + DIAG_INHAT + DIAG_DEP + DIAG_MANIA + DIAG_ADHD + DIAG_CD + DIAG_ODD + DIAG_EAT + DIAG_AUTISM + DIAG_TIC +  DIAG_PSYCH | Gender, data = test_database_wave3)
```

## IPW for missing data

### Setting up data

```{r}

# Geração de pesos de probabilidade inversa = pesos a pessoas com maior probabilidade de não estarem sendo representadas no banco = aumenta a representatividade da amostra

# Variável de retenção (sim = quem ficou; é o inverso do missing)
bhrc_database_ipw_mfq <- bhrc_database %>% mutate(attrition_MFQ= case_when(p_mfqtot!="NA" ~ "Yes", TRUE ~ "No"))
# Inverse probability weight para variável de medida escolhida

# Ordinal, o sim vale mais que o não
bhrc_database_ipw_mfq <- bhrc_database_ipw_mfq %>% mutate_at(vars("attrition_MFQ"),factor)
bhrc_database_ipw_mfq$attrition_MFQ <- ordered(bhrc_database_ipw_mfq$attrition_MFQ)
summary.factor(bhrc_database_ipw_mfq$attrition_MFQ)

bhrc_database_ipw_mfq <- bhrc_database_ipw_mfq %>%
  select(ident, attrition_MFQ)

bhrc_database_ipw_mfq <- left_join(bhrc_database_ipw_mfq, test_database_wave1, by="ident")

# Excluindo variáveis com muitos missings ou não necessários
bhrc_database_ipw_mfq <- bhrc_database_ipw_mfq %>%
  select(-instlevel:-finstlevel, -foccupation, -Income_mother, -Income_father, -Conviction, -abepstrat, -Studying)

# Filter to complete data in variable with less complete baseline data
test_bhrc_database_ipw_mfq <- bhrc_database_ipw_mfq[complete.cases(bhrc_database_ipw_mfq), ]
summary.factor(test_bhrc_database_ipw_mfq$attrition_MFQ)

## Descriptive (!!!!!!!!!) quem não ficou VS quem ficou no estudo, com base no baseline
table1(~ Age + Gender + Selection + Site + Child_race + Child_race_2cat + minstlevel_4cat + SEG + Birth_weight + Educ_level_current + Educ_attainment + NEET_all + moccupation + Assistance_any + Assistance_type + Income_total + Maternal_DIAG_ANY +  abepscore | attrition_MFQ, data = test_bhrc_database_ipw_mfq, overall=FALSE)
```

### NOT WORKING - Regression and IPW (código DCG)

```{r}
## Logit regression
# As outras variáveis dão erro no modelo...
fit_ipw_mfq <- glm(attrition_MFQ ~ Age + Gender + Selection + Site + Child_race + minstlevel_4cat + SEG + Birth_weight + moccupation + Assistance_any + Income_total + Maternal_DIAG_ANY + abepscore, family=binomial(link='logit'), data=test_bhrc_database_ipw_mfq)

summary(fit_ipw_mfq)
tab_model(fit_ipw_mfq)
# Estimate está em log odds, para saber odds ratio exponenciar

## Predicted
pw_mfq <- predict(fit_ipw_mfq, type="response")
# Função para predizer a probabilidade de cada um ficar no estudo

## Invert prediction - quem ficar no estudo mas tinha mais chances de abandonar precisa representar mais nos dados
ipw_mfq <- 1/pw_mfq

## Add to temporary data set - clicar na tabela para visualizar
bhrc_database_ipw_mfq <- cbind(test_bhrc_database_ipw_mfq,ipw_mfq) %>% dplyr::select(subjectid, ipw_mfq, attrition_MFQ)

### Testar se o peso deu certo - deve-se somar todos os pesos no banco das pessoas que ficaram e ver se o resultado dá o mesmo do n inicial
bhrc_database_ipw_mfq_test<- bhrc_database_ipw_mfq %>% filter(attrition_MFQ=="Yes")
sum(bhrc_database_ipw_mfq_test$ipw_mfq)  
#Should be = 1991 (complete variables at baseline), but is 4762.633
```

### WORKING - WeightIt package

```{r}
weights_weightit <- weightit(attrition_MFQ ~ Age + Gender + Selection + Site + Child_race + minstlevel_4cat + SEG + Birth_weight + moccupation + Assistance_any + Income_total + Maternal_DIAG_ANY + abepscore,  # Model net use with confounders
                             data = test_bhrc_database_ipw_mfq, 
                             estimand = "ATE",  # Find the ATE
                             method = "ps")  # Build weights with propensity scores

weights_weightit
head(weights_weightit$weights)
test_bhrc_database_ipw_mfq$ipw <- weights_weightit$weights

### Testar se o peso deu certo - deve-se somar todos os pesos no banco das pessoas que ficaram e ver se o resultado dá o mesmo do n inicial
bhrc_database_ipw_mfq_test2<- test_bhrc_database_ipw_mfq %>% filter(attrition_MFQ=="Yes")
sum(bhrc_database_ipw_mfq_test2$ipw)

#Should be = 1991 (complete variables at baseline), and is 1991.336
```

## Descriptives

### Diagnose x characteristics (wave==3)

```{r}
# Linhas: variáveis sociodemograficas da onda 2, diagnóstico materno do baseline, escore somado da MFQ, diagnósticos prevalentes
# Colunas: Nenhum diagóstico, diagnóstico de depressão, e qualquer diagnóstico (DIAG_ANY). Tem que construir essa variavel.

# Combining Maternal diagnose with wave==3 data
temp_database <- test_database_wave1 %>% select(ident, Maternal_DIAG_ANY)
bhrc_database <- left_join(bhrc_database, temp_database, by="ident")

# Combining DIAG_PANIC and DIAG_AGORAPHOBIA
bhrc_database$DIAG_PANIC_AGORAPHOB <- ifelse(bhrc_database$DIAG_PANIC == 1 | bhrc_database$DIAG_AGORAPHOB == 1, 1, 0)

# DIAG_TYPE
bhrc_database <- bhrc_database %>%
  mutate(DIAG_TYPE = case_when(
    DIAG_ANY == 'No' ~ 0,
    DIAG_ANY == 'Yes' & DIAG_DEP == 1 ~ 1,
    DIAG_ANY == 'Yes' & DIAG_DEP == 0 ~ 2,
    TRUE ~ 3
  ))

# Convertendo para fator e adicionando labels à variável DIAG_TYPE
bhrc_database$DIAG_TYPE <- factor(bhrc_database$DIAG_TYPE, levels = c(0, 1, 2, 3), labels = c("Nenhum diagnóstico", "Possui diagnóstico, incluindo depressão", "Possui diagnóstico, sem depressão", "Sem dados"))

# TABELA DESCRITIVA
# Variáveis demográficas úteis: Age, Gender, Selection, Site, Child_race, SEG, Studying, work, instlevel, minstlevel_4cat, finstlevel, moccupation, foccupation, Assistance_any, Assistance_type, Income_total, Conviction, abepscore
# Diagnósticos com >2% prevalência: DIAG_SOC_PHOB + DIAG_PANIC_AGORAPHOB + DIAG_PTSD + DIAG_GEN_ANX + DIAG_DEP + DIAG_ADHD + DIAG_CD

table1(~Age + Gender + Selection + Site + Child_race + SEG  + abepscore + Studying + work + instlevel + minstlevel_4cat + finstlevel + moccupation + foccupation + Assistance_any + Assistance_type + Income_total + Conviction + Maternal_DIAG_ANY + p_mfqtot + DIAG_SOC_PHOB + DIAG_PANIC_AGORAPHOB + DIAG_PTSD + DIAG_GEN_ANX + DIAG_DEP + DIAG_ADHD + DIAG_CD | DIAG_TYPE, data = bhrc_database)
```

## EFA

```{r}
library(psych)
library(ggcorrplot)
library(polycor)

# Selecting variables and Transforming to numeric
EFA_data_MFQ <- bhrc_database %>% dplyr::select(p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13) %>% mutate_all(~as.character(.) %>% as.numeric())

# Substituindo por NA aqueles que responderam 99
EFA_data_MFQ <- EFA_data_MFQ %>%
  mutate_at(vars(p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13), 
            ~ ifelse(. == 99, NA, .))
EFA_data_MFQ <- EFA_data_MFQ[complete.cases(EFA_data_MFQ[ ,1]),]

# Calculating polychoric matrix
EFA_data_MFQ_matrix <- psych::mixedCor(EFA_data_MFQ, smooth=TRUE)
EFA_data_MFQ_poly <- EFA_data_MFQ_matrix$rho

# Plotting polychoric correlation matrix
ggcorrplot(EFA_data_MFQ_poly)

# How Factorable is our Dataset?

## Bartlett test - p<0.05
cortest.bartlett(EFA_data_MFQ_poly, n=1626) # p=0

## Kaiser-Meyer-Olkin factor adequacy - MSA must be closer to 1.0 (0 to 1)
KMO(EFA_data_MFQ_poly) # MSA = 0.96

# Exploring the number of factors using scree plot
fa.parallel(EFA_data_MFQ_poly, n.obs =1626, fa = "fa", fm="wls") # 1 factor

## EFA based on parallel analysis resutls
EFA_data_MFQ_poly_2f <- psych::fa(EFA_data_MFQ_poly, nfactors = 1, fm="wls", rotate = "oblimin", np.obs=1626)
EFA_data_MFQ_poly_2f
fa.diagram(EFA_data_MFQ_poly_2f)
```

## CFA

```{r}
library(lavaan)
library(semPlot)

## 1 Factor Model
MFQ_model_1F <- 'General_1F =~ p_mfq1 + p_mfq2 + p_mfq3 + p_mfq4 + p_mfq5 + p_mfq6 + p_mfq7 +  p_mfq8 + p_mfq9 + p_mfq10 + p_mfq11 + p_mfq12 + p_mfq13'

# Fitting the model
fit_MFQ_1F <- cfa(MFQ_model_1F, data=EFA_data_MFQ, ordered = T, std.lv=T, estimator="WLSMV")
summary(fit_MFQ_1F,fit.measures=T, standardized=T, rsquare=T)

# Reliability
semTools::reliability(fit_MFQ_1F)

# Graph
semPaths(fit_MFQ_1F, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2,) # Technical representation

# Modification indices
Mod_Indices_MFQ_model_1F <- modindices(fit_MFQ_1F, sort = TRUE, maximum.number = 10)
Mod_Indices_MFQ_model_1F[Mod_Indices_MFQ_model_1F$op == "~~",]

## 3 Factor Model
MFQ_model_3F <- 'Negative_self_ev =~ p_mfq5 +  p_mfq8 +  p_mfq9 + p_mfq10 + p_mfq11 + p_mfq12 + p_mfq13
Negative_mood =~ p_mfq1 + p_mfq2 + p_mfq6
Rest_tired_conc =~ p_mfq3 + p_mfq4 + p_mfq7'

# Fitting the model
fit_MFQ_3F <- cfa(MFQ_model_3F, data=EFA_data_MFQ, ordered = T, std.lv = T, estimator="WLSMV")
summary(fit_MFQ_3F,fit.measures=T, standardized=T, rsquare=T)

# Modification indices
Mod_Indices_MFQ_3F <- modindices(fit_MFQ_3F, sort = TRUE, maximum.number = 10)
Mod_Indices_MFQ_3F[Mod_Indices_MFQ_3F$op == "~~",]

#Reliability
semTools::reliability(fit_MFQ_3F)

##Graph
semPaths(fit_MFQ_3F, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2,) 

# Technical representation
semPaths(fit_MFQ_3F, residuals=F, intercepts = F,sizeMan=6,"std",
         posCol=c("skyblue3", "red"),
         #edge.color="skyblue4",
         edge.label.cex=1.2,layout="circle")

## Bifactor
MFQ_model_bif <- 'Negative_self_ev =~ p_mfq5 +  p_mfq8 +  p_mfq9 + p_mfq10 + p_mfq11 + p_mfq12 + p_mfq13
Negative_mood =~ p_mfq1 + p_mfq2 + p_mfq6
Rest_tired_conc =~ p_mfq3 + p_mfq4 + p_mfq7
General_bif =~ p_mfq1 + p_mfq2 + p_mfq3 + p_mfq4 + p_mfq5 + p_mfq6 + p_mfq7 +  p_mfq8 + p_mfq9 + p_mfq10 + p_mfq11 + p_mfq12 + p_mfq13'

# Fitting the model
fit_MFQ_bif <- cfa(MFQ_model_bif, data=EFA_data_MFQ, ordered = T, std.lv = T, estimator="WLSMV")
summary(fit_MFQ_bif,fit.measures=T, standardized=T, rsquare=T)

# Modification indices
Mod_Indices_MFQ_bif <- modindices(fit_MFQ_bif, sort = TRUE, maximum.number = 10)
Mod_Indices_MFQ_bif[Mod_Indices_MFQ_bif$op == "~~",]

#Reliability
semTools::reliabilityL2(fit_MFQ_bif, General_2nd)
##Graph
semPaths(fit_MFQ_bif, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2) 

# Model comparison
lavTestLRT(fit_MFQ_1F, fit_MFQ_3F)
```

## IRT

```{r}
library(ltm)
library(mirt)
library(ggpubr)

irt_mfq_total <- EFA_data_MFQ

# Total scores
items_mfq <- list(MFQ_Total=c("p_mfq1","p_mfq2","p_mfq3","p_mfq4","p_mfq5", "p_mfq6","p_mfq7","p_mfq8","p_mfq9","p_mfq10","p_mfq11","p_mfq12","p_mfq13"))
score_mfq <- scoreItems(items_mfq,irt_mfq_total,totals = T) 
irt_mfq_total$MFQ_Total<-as.numeric(score_mfq$scores[,1])
hist(irt_mfq_total$MFQ_Total)

bhrc_database$p_mfqtot_no99 <- irt_mfq_total$MFQ_Total

# IRT
## Graded Response Model - unidimensional

irt_mfq <- irt_mfq_total %>% select(p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13) %>% mutate_all(~as.character(.) %>% as.numeric())
MFQ_1F_grm <- grm(irt_mfq)
plot(MFQ_1F_grm, type = "IIC", items = 0, main="MFQ general information curve", ylab = "Information", xlab = "Depression latent trait")

# Characteristic of the instrument
par(mfrow = c(3, 3))
plot(MFQ_1F_grm,type="ICC")
par(mfrow = c(1, 1))

# Information  of the instrument
plot(MFQ_1F_grm,type="IIC", main="MFQ item information curve", ylab = "Information", xlab = "Depression latent trait")

#Psych IRT (Reliability by area of the latent trait)
irt.fa(irt_mfq)

#Loadings
summary(MFQ_1F_grm) #AIC e BIC

# coefficients
coef(MFQ_1F_grm)

## IRT score
MFQ_1F_grm_fs<-factor.scores.grm(MFQ_1F_grm, resp.patterns = irt_mfq)
MFQ_1F_grm_fs<-MFQ_1F_grm_fs$score.dat$z1
MFQ_1F_grm_fs<-as.data.frame(MFQ_1F_grm_fs)
irt_mfq$MFQ_1F_fs<-MFQ_1F_grm_fs[,1]
hist(irt_mfq$MFQ_1F_fs)
summary(irt_mfq$MFQ_1F_fs)

# Combine total and IRT-based factor score
mfq_total_uni <- cbind(irt_mfq_total, irt_mfq) %>% dplyr::select(MFQ_Total, MFQ_1F_fs)
# Correlation between total and factor scores
plot(mfq_total_uni$MFQ_Total,mfq_total_uni$MFQ_1F_fs, main="Correlation between MFQ total and IRT-based factor score", ylab = "MFQ factor score", xlab = "MFQ total score")

ggscatter(mfq_total_uni, x = "MFQ_Total", y = "MFQ_1F_fs", 
          add = "reg.line", conf.int = T, 
          cor.coef = T, cor.method = "pearson",
          xlab = "MFQ total score", ylab = "MFQ factor score", 
          main="Correlation between MFQ total and IRT-based factor score")
```

## ROC curves

```{r}
#install.packages("pROC")
library(pROC)

# Selecting variables and transforming to numeric
mfq_roc <- bhrc_database %>% dplyr::select(ident, DIAG_ANY, DIAG_SOC_PHOB, DIAG_PANIC_AGORAPHOB, DIAG_PTSD, DIAG_GEN_ANX, DIAG_DEP, DIAG_ADHD, DIAG_CD, p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13)

# Substituindo por NA aqueles que responderam 99
mfq_roc <- mfq_roc %>%
  mutate_at(vars(p_mfq1, p_mfq2, p_mfq3, p_mfq4, p_mfq5, p_mfq6, p_mfq7, p_mfq8, p_mfq9, p_mfq10, p_mfq11, p_mfq12, p_mfq13), 
            ~ ifelse(. == 99, NA, .))
mfq_roc <- mfq_roc[complete.cases(mfq_roc), ]
mfq_roc$p_mfqtot_no99 <- rowSums(mfq_roc[, c("p_mfq1", "p_mfq2", "p_mfq3", "p_mfq4", "p_mfq5", "p_mfq6", "p_mfq7", "p_mfq8", "p_mfq9", "p_mfq10", "p_mfq11", "p_mfq12", "p_mfq13")], na.rm = TRUE)

# DIAG_ANY
roc_ANY <- roc(mfq_roc$DIAG_ANY, mfq_roc$p_mfqtot_no99)
plot(roc_ANY, main = "Curva ROC", col = "blue", lwd = 2, print.thres=T) #Ponto de corte = 0.7
auc_ANY <- auc(roc_ANY)
cat("Área Sob a Curva (AUC):", auc_ANY, "\n")

# DIAG_DEP
roc_DEP <- roc(mfq_roc$DIAG_DEP, mfq_roc$p_mfqtot_no99)
plot(roc_DEP, main = "Curva ROC - DEP", col = "blue", lwd = 2, print.thres=T)
auc_DEP <- auc(roc(mfq_roc$DIAG_DEP, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para DEP:", auc_DEP, "\n")

#DIAG_SOC_PHOBIA
roc_SOC_PHOB <- roc(mfq_roc$DIAG_SOC_PHOB, mfq_roc$p_mfqtot_no99)
plot(roc_SOC_PHOB, main = "Curva ROC", col = "blue", lwd = 2, print.thres=T)
auc_SOC_PHOB <- auc(roc(mfq_roc$DIAG_SOC_PHOB, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para SOC_PHOB:", auc_SOC_PHOB, "\n")

# DIAG_PANIC_AGORAPHOB
roc_PANIC_AGORAPHOB <- roc(mfq_roc$DIAG_PANIC_AGORAPHOB, mfq_roc$p_mfqtot_no99)
plot(roc_PANIC_AGORAPHOB, main = "Curva ROC - PANIC_AGORAPHOB", col = "blue", lwd = 2, print.thres=T)
auc_PANIC_AGORAPHOB <- auc(roc(mfq_roc$DIAG_PANIC_AGORAPHOB, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para PANIC_AGORAPHOB:", auc_PANIC_AGORAPHOB, "\n")

# DIAG_PTSD
roc_PTSD <- roc(mfq_roc$DIAG_PTSD, mfq_roc$p_mfqtot_no99)
plot(roc_PTSD, main = "Curva ROC - PTSD", col = "blue", lwd = 2, print.thres=T)
auc_PTSD <- auc(roc(mfq_roc$DIAG_PTSD, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para PTSD:", auc_PTSD, "\n")

# DIAG_GEN_ANX
roc_GEN_ANX <- roc(mfq_roc$DIAG_GEN_ANX, mfq_roc$p_mfqtot_no99)
plot(roc_GEN_ANX, main = "Curva ROC - GEN_ANX", col = "blue", lwd = 2, print.thres=T, print.thres=T)
auc_GEN_ANX <- auc(roc(mfq_roc$DIAG_GEN_ANX, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para GEN_ANX:", auc_GEN_ANX, "\n")

# DIAG_ADHD
roc_ADHD <- roc(mfq_roc$DIAG_ADHD, mfq_roc$p_mfqtot_no99)
plot(roc_ADHD, main = "Curva ROC - ADHD", col = "blue", lwd = 2, print.thres=T)
auc_ADHD <- auc(roc(mfq_roc$DIAG_ADHD, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para ADHD:", auc_ADHD, "\n")

# DIAG_CD
roc_CD <- roc(mfq_roc$DIAG_CD, mfq_roc$p_mfqtot_no99)
plot(roc_CD, main = "Curva ROC - CD", col = "blue", lwd = 2, print.thres=T)
auc_CD <- auc(roc(mfq_roc$DIAG_CD, mfq_roc$p_mfqtot_no99))
cat("Área Sob a Curva (AUC) para CD:", auc_CD, "\n")
```
